apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    name: guestbook-service
    app: guestbook-app
spec:
  type: LoadBalancer # to access from outside
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: guestbook-pod
    app: guestbook-app
