apiVersion: v1
kind: Service
metadata:
  name: business-redis
  labels:
    name: business-redis-service
    app: guestbook-app
    tier: business
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: business-redis-pod
    app: guestbook-app
    tier: business
