apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: guestbook-app
    tier: private
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: guestbook-app
      tier: private
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guestbook-app
        tier: private
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
