apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-redis-deployment
  labels:
    app: guestbook-app
    tier: business
spec:
  replicas: 3
  selector:
    matchLabels:
      name: business-redis-pod
      app: guestbook-app
      tier: business
  template:
    metadata:
      name: business-redis-pod
      labels:
        name: business-redis-pod
        app: guestbook-app
        tier: business
    spec:
      containers:
        - name: business-redis
          image: redis
          ports:
            - containerPort: 6379
